@startuml bot
start
#palegreen:Введи название бота;

if (Новый пользователь?) then (Да)
    #gold:Первое приветствие, знакомство с ботом|
else (Нет)

    if (Проверка чата) then (Чат удален)
        #gold:Вывести приветсвие;
        else (Чат активен)
        #gold:%вывести последнюю информацию%;
    endif

endif


repeat
#SkyBlue:Вывод меню бота;
if (Вывод кнопок) then
    #palegreen:Показать всю библиотеку;
    #gold:Вывод всех книг с БД;
else
    #palegreen:Поиск книги по нзванию;

    if (Такая книга есть?) then (Нет)
        #gold:Возможно в скором времени книга появится в библиотеке;
    else (Да)
        #gold:Вывод искомой книги;
    endif
endif

repeat while (Вернуться в меню?) is (Да) not (нет)
:Удалить бота;
end

@enduml
