@startuml
start
:открой на смартфоне 2гис;
:найди булочную;
:войди в булочную;
if (есть ли в продаже свежие круассаны?) then (да)
:купи круассан;
else (нет)
:изрыгни проклятье;
endif
:выйди из булочной;
:дойди до дома;
:войди в дом;
:съешь круассан;
:ляг спать;
end
@enduml
