@startuml
start
:Возьми чайник;
while (Есть вода в чайнике?) is (нет)
:Наполни чайник водой;
endwhile (да)
:Нажми кнопку включения;
if (Чайник скипел?) then (да)
else (нет)
:Подожди еще;
endif
:Возьми пустую кружку;
if (Что хочешь выпить?) then (Кофе)
:Положи ложку кофе;
else (Чай)
:Положи в кружку чайный пакетик;
endif
:Залей в кружку горячую воду;
repeat
:Положи сахар и размешай;
:Попробуй;
repeat while (Достаточно сладкий?) is (нет) not (да)
:Выпей чай;
end
@enduml
